EXEC Procedures_AdminIssueInstallment
EXEC Procedures_AdminDeleteCourse
EXEC Procedure_AdminUpdateStudentStatus
EXEC all_Pending_Requests
EXEC Procedures_AdminDeleteSlots
EXEC Procedures_AdvisorCreateGP
EXEC Procedures_AdvisorAddCourseGP
EXEC Procedures_AdvisorUpdateGP
EXEC Procedures_AdvisorDeleteFromGP

DROP PROC Procedures_AdminIssueInstallment
DROP PROC Procedures_AdminDeleteCourse
DROP PROC Procedure_AdminUpdateStudentStatus
DROP VIEW all_Pending_Requests
DROP PROC Procedures_AdminDeleteSlots
DROP PROC Procedures_AdvisorCreateGP
DROP PROC Procedures_AdvisorAddCourseGP
DROP PROC Procedures_AdvisorUpdateGP
DROP PROC Procedures_AdvisorDeleteFromGP
DROP FUNCTION FN_AdvisorLogin 

EXEC CreateAllTables